/*
   Copyright (C) 2026 Kitsas contributors

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
*/
#include "sqlitetuoja.h"
#include "sql/sqlmodel.h"

#include <QApplication>
#include <QJsonDocument>
#include <QJsonParseError>
#include <QMessageBox>
#include <QProgressDialog>
#include <QSqlError>
#include <QSqlQuery>
#include <QUuid>

namespace {

struct Taulu {
    QString nimi;
    QStringList sarakkeet;
};

// Taulut vieraan avaimen kannalta turvallisessa järjestyksessä. Sarakeluettelot
// on kirjoitettu käsin nykyisen skeeman mukaan (ei koskaan johdettu lähdetiedoston
// omista sarakenimistä), jotta väärennetty/vioittunut tiedosto ei voi injektoida
// SQL:ää saraketietojen kautta.
const QVector<Taulu> TAULUT = {
    { QStringLiteral("Asetus"),     {"avain","arvo","muokattu"} },
    { QStringLiteral("Tili"),       {"numero","tyyppi","iban","json","muokattu"} },
    { QStringLiteral("Otsikko"),    {"numero","taso","json","muokattu"} },
    { QStringLiteral("Tilikausi"),  {"alkaa","loppuu","json"} },
    { QStringLiteral("Kohdennus"),  {"id","tyyppi","kuuluu","json"} },
    { QStringLiteral("Budjetti"),   {"tilikausi","kohdennus","tili","sentti"} },
    { QStringLiteral("Kumppani"),   {"id","nimi","alvtunnus","json"} },
    { QStringLiteral("KumppaniIban"), {"iban","kumppani"} },
    { QStringLiteral("Ryhma"),      {"id","nimi","json"} },
    { QStringLiteral("KumppaniRyhmassa"), {"kumppani","ryhma"} },
    { QStringLiteral("Tosite"),     {"id","pvm","tyyppi","tila","tunniste","sarja","otsikko","kumppani","laskupvm","erapvm","viite","json"} },
    { QStringLiteral("Tositeloki"), {"id","tosite","aika","data","userid","tila"} },
    { QStringLiteral("Vienti"),     {"id","rivi","tosite","tyyppi","pvm","tili","kohdennus","selite","debetsnt","kreditsnt","eraid","alvprosentti","alvkoodi","kumppani","jaksoalkaa","jaksoloppuu","arkistotunnus","json"} },
    { QStringLiteral("Merkkaus"),   {"vienti","kohdennus"} },
    { QStringLiteral("Liite"),      {"id","tosite","nimi","roolinimi","tyyppi","sha","data","luotu","json"} },
    { QStringLiteral("Tuote"),      {"id","nimike","json"} },
    { QStringLiteral("Rivi"),       {"tosite","rivi","tuote","myyntikpl","ostokpl","ahinta","json"} },
    { QStringLiteral("Vakioviite"), {"viite","tili","kohdennus","otsikko","alkaen","paattyen","json"} },
};

// Postgresin GENERATED BY DEFAULT AS IDENTITY -sarakkeet: kun rivit tuodaan
// alkuperäisillä id:illä ohi sekvenssin, sekvenssi pitää synkronoida jälkikäteen,
// tai seuraava tavallinen INSERT törmää jo käytettyyn id:hen.
const QStringList IDENTITEETTITAULUT = {
    QStringLiteral("Kohdennus"), QStringLiteral("Kumppani"), QStringLiteral("Ryhma"),
    QStringLiteral("Tosite"), QStringLiteral("Tositeloki"), QStringLiteral("Vienti"),
    QStringLiteral("Liite"), QStringLiteral("Tuote")
};

// Tositeloki.data on ainoa aidosti jsonb-tyyppinen sarake. SQLiten "jsonb"-tyyppimääre
// ei vastaa mitään SQLiten tunnistamaa affiniteettia, joten se päätyy NUMERIC-affiniteettiin:
// jos sisältö sattuu näyttämään puhtaalta numerolta, SQLite saattaa tallentaa sen numerona
// tekstin sijaan. Postgres taas vaatii aidosti kelvollista JSONia joka rivillä. Palautetaan
// aina merkkijonona, tai NULL jos sisältö on tyhjä tai ei jäsenny JSONiksi.
QVariant siivoaJsonb(const QVariant& arvo)
{
    if( arvo.isNull())
        return QVariant();
    const QString teksti = arvo.toString();
    if( teksti.isEmpty())
        return QVariant();
    QJsonParseError virhe;
    QJsonDocument::fromJson(teksti.toUtf8(), &virhe);
    if( virhe.error != QJsonParseError::NoError) {
        qWarning() << "SqliteTuoja: Tositeloki.data ei ole kelvollista JSONia, tallennetaan NULL:" << virhe.errorString();
        return QVariant();
    }
    return teksti;
}

bool kopioiTaulu(QSqlDatabase& sqlite, QSqlDatabase& postgres, const Taulu& taulu, QString* virhe)
{
    QSqlQuery lue(sqlite);
    if( !lue.exec(QStringLiteral("SELECT %1 FROM %2").arg(taulu.sarakkeet.join(','), taulu.nimi)) ) {
        *virhe = lue.lastError().text();
        return false;
    }

    const bool onTositeloki = (taulu.nimi == QLatin1String("Tositeloki"));
    const int jsonbSarake = onTositeloki ? taulu.sarakkeet.indexOf(QLatin1String("data")) : -1;

    // Liite.tosite=0 on vanha "ei liity mihinkään tositteeseen" -merkintä
    // (esim. tilinpäätöstekstin liitteet, ks. TilinpaatosEditori), jota SQLite
    // on päästänyt läpi koska se ei oletuksena valvo FK-rajoitteita. Postgres
    // valvoo aina, eikä id 0 vastaa mitään Tosite-riviä, joten arvo tulkitaan
    // NULL:ksi tuonnissa vastaamaan sen todellista merkitystä.
    const bool onLiite = (taulu.nimi == QLatin1String("Liite"));
    const int tositeSarake = onLiite ? taulu.sarakkeet.indexOf(QLatin1String("tosite")) : -1;
    const int liiteDataSarake = onLiite ? taulu.sarakkeet.indexOf(QLatin1String("data")) : -1;

    QList<QVariantList> rivit;
    while( lue.next()) {
        QVariantList rivi;
        for(int i=0; i < taulu.sarakkeet.count(); i++) {
            QVariant arvo = lue.value(i);
            if( onTositeloki && i == jsonbSarake ) {
                arvo = siivoaJsonb(arvo);
            } else if( onLiite && i == tositeSarake && arvo.toInt() == 0 ) {
                arvo = QVariant();
            } else if( !(onLiite && i == liiteDataSarake) && arvo.typeId() == QMetaType::QByteArray ) {
                // Liite.data on skeeman ainoa aidosti binäärinen sarake. Jos SQLite
                // palauttaa jonkin toisen sarakkeen silti QByteArray-tyyppisenä, se on
                // merkki siitä, että arvo on aikoinaan kirjoitettu virheellisesti
                // QByteArray-sidonnalla teksti-/jsonb-sarakkeeseen (sama vanha bugi kuin
                // mapToJson()/LiitteetRoute::hash():ssa, ks. niiden kommentit) - SQLite ei
                // valvo sarakkeen tyyppiä, joten arvo tallentui BLOB-muodossa TEXT-sarakkeeseen
                // näkymättömästi. Tulkitaan UTF-8-tekstiksi, ettei Postgresin QPSQL-ajuri
                // sarjallista sitä bytea-heksana kohdesarakkeeseen.
                arvo = QString::fromUtf8(arvo.toByteArray());
            }
            rivi.append(arvo);
        }
        rivit.append(rivi);
    }

    if( rivit.isEmpty())
        return true;

    // Monirivinen INSERT paloitellaan kahdella rajalla:
    //  - rivimäärä pidetään turvamarginaalilla Postgresin 65535 parametrin
    //    protokollarajasta, sama periaate kuin TositeRoute::lisaaTaiPaivita:ssa;
    //  - tavumäärä rajoitetaan erikseen, koska esim. Liite.data voi olla suuria
    //    liitetiedostoja - ilman tätä tuhannet liitteet voisivat päätyä yhteen
    //    satojen megatavujen kyselyyn, joka on hidas lähettää ja käsitellä.
    const int maxRivia = qMax(1, 50000 / taulu.sarakkeet.count());
    const qint64 maxTavuja = 20 * 1024 * 1024; // 20 Mt / kysely

    auto rivinPaino = [](const QVariantList& rivi) -> qint64 {
        qint64 paino = 0;
        for(const QVariant& arvo : rivi) {
            switch(arvo.typeId()) {
            case QMetaType::QByteArray:
                paino += arvo.toByteArray().size();
                break;
            case QMetaType::QString:
                paino += arvo.toString().size() * 2; // karkea arvio
                break;
            default:
                paino += 8;
            }
        }
        return paino;
    };

    const QString paikkaRivi = QStringLiteral("(%1)").arg(
                QStringList(taulu.sarakkeet.count(), QStringLiteral("?")).join(','));

    int alku = 0;
    while( alku < rivit.count()) {
        int maara = 0;
        qint64 paino = 0;
        while( alku+maara < rivit.count() && maara < maxRivia ) {
            const qint64 rivinTavut = rivinPaino(rivit.at(alku+maara));
            if( maara > 0 && paino + rivinTavut > maxTavuja )
                break;
            paino += rivinTavut;
            maara++;
        }

        QStringList paikat;
        for(int i=0; i < maara; i++)
            paikat << paikkaRivi;

        QSqlQuery kirjoita(postgres);
        kirjoita.prepare(QStringLiteral("INSERT INTO %1 (%2) VALUES %3 ON CONFLICT DO NOTHING")
                         .arg(taulu.nimi, taulu.sarakkeet.join(','), paikat.join(',')));

        for(int i=alku; i < alku+maara; i++)
            for(const QVariant& arvo : rivit.at(i))
                kirjoita.addBindValue(arvo);

        if( !kirjoita.exec()) {
            *virhe = kirjoita.lastError().text();
            return false;
        }
        alku += maara;
    }
    return true;
}

} // namespace

bool SqliteTuoja::tuo(QSqlDatabase postgres, const QString &sqlitePolku, bool ilmoitaVirheesta)
{
    const QString lahdeYhteysNimi = QStringLiteral("KITSAS_TUONTI_LAHDE_") + QUuid::createUuid().toString(QUuid::Id128);
    QSqlDatabase sqlite = QSqlDatabase::addDatabase(QStringLiteral("QSQLITE"), lahdeYhteysNimi);
    sqlite.setDatabaseName(sqlitePolku);

    auto lopeta = [&](bool tulos) {
        if( sqlite.isOpen())
            sqlite.close();
        sqlite = QSqlDatabase();
        QSqlDatabase::removeDatabase(lahdeYhteysNimi);
        return tulos;
    };

    const QString otsikko = QObject::tr("SQLiten tuonti epäonnistui");
    auto ilmoita = [&](const QString& viesti) {
        // Lokitetaan aina - myös silloin kun valintaikkuna on tukahdutettu
        // (esim. taustaprosessissa), jotta virhe ei jää täysin näkymättömiin.
        qWarning() << "SqliteTuoja:" << viesti;
        if( ilmoitaVirheesta )
            QMessageBox::critical(nullptr, otsikko, viesti);
    };

    if( !sqlite.open()) {
        ilmoita(QObject::tr("Tiedostoa %1 ei voitu avata SQLite-tietokantana.\n%2")
                .arg(sqlitePolku, sqlite.lastError().text()));
        return lopeta(false);
    }

    // Varmistetaan, että lähde on aidosti Kitsas-tietokanta ja täsmälleen nykyistä
    // skeemaversiota. Vanhempien tiedostojen ALTER TABLE -päivityslogiikkaa ei toisteta
    // tässä - käyttäjää pyydetään avaamaan tiedosto ensin tavallisesti Kitsaassa.
    QSqlQuery versiokysely(sqlite);
    if( !versiokysely.exec(QStringLiteral("SELECT arvo FROM Asetus WHERE avain='KpVersio'")) || !versiokysely.next()) {
        ilmoita(QObject::tr("Tiedosto %1 ei ole Kitsaan tietokanta.").arg(sqlitePolku));
        return lopeta(false);
    }
    const int versio = versiokysely.value(0).toInt();
    if( versio != SqlModel::TIETOKANTAVERSIO) {
        ilmoita(QObject::tr("Tietokanta on versiota %1, mutta tuonti vaatii version %2. "
                           "Avaa tiedosto ensin tavallisesti Kitsaassa päivittääksesi sen, ja yritä tuontia uudelleen.")
                .arg(versio).arg(SqlModel::TIETOKANTAVERSIO));
        return lopeta(false);
    }

    QProgressDialog edistyminen(QObject::tr("Tuodaan tietoja SQLite-tiedostosta..."), QString(), 0, TAULUT.count() + 1);
    edistyminen.setWindowModality(Qt::WindowModal);
    edistyminen.setMinimumDuration(0);

    if( !postgres.transaction()) {
        ilmoita(QObject::tr("Postgres-tapahtuman aloitus epäonnistui.\n%1").arg(postgres.lastError().text()));
        return lopeta(false);
    }

    int vaihe = 0;
    for(const Taulu& taulu : TAULUT) {
        edistyminen.setLabelText(QObject::tr("Tuodaan taulua %1...").arg(taulu.nimi));
        edistyminen.setValue(vaihe++);
        qApp->processEvents();

        QString virhe;
        if( !kopioiTaulu(sqlite, postgres, taulu, &virhe) ) {
            postgres.rollback();
            ilmoita(QObject::tr("Virhe taulua %1 tuotaessa:\n%2").arg(taulu.nimi, virhe));
            return lopeta(false);
        }
    }

    edistyminen.setLabelText(QObject::tr("Synkronoidaan tunnisteita..."));
    edistyminen.setValue(vaihe++);
    qApp->processEvents();

    for(const QString& taulu : IDENTITEETTITAULUT) {
        QSqlQuery maxKysely(postgres);
        if( !maxKysely.exec(QStringLiteral("SELECT MAX(id) FROM %1").arg(taulu)) || !maxKysely.next()) {
            postgres.rollback();
            ilmoita(QObject::tr("Taulun %1 suurimman id:n haku epäonnistui.\n%2")
                    .arg(taulu, maxKysely.lastError().text()));
            return lopeta(false);
        }
        const qlonglong suurinId = maxKysely.value(0).toLongLong();
        if( suurinId <= 0 )
            continue;   // Ei tuotuja rivejä (tai vain id=0 -siemenrivi) - koskematon
                        // sekvenssi alkaa jo oikein arvosta 1, eikä setval hyväksyisi 0:aa.

        QSqlQuery resync(postgres);
        if( !resync.exec(QStringLiteral("SELECT setval(pg_get_serial_sequence('%1','id'), %2)")
                         .arg(taulu).arg(suurinId)) ) {
            postgres.rollback();
            ilmoita(QObject::tr("Taulun %1 tunnistesarjan synkronointi epäonnistui.\n%2")
                    .arg(taulu, resync.lastError().text()));
            return lopeta(false);
        }
    }

    if( !postgres.commit()) {
        postgres.rollback();
        ilmoita(QObject::tr("Postgres-tapahtuman tallennus epäonnistui.\n%1").arg(postgres.lastError().text()));
        return lopeta(false);
    }

    edistyminen.setValue(TAULUT.count() + 1);
    return lopeta(true);
}
